version: 2
registries:
  npm-registry-npm-registry-harpokrat-net:
    type: npm-registry
    url: https://npm-registry.harpokrat.net
    token: "${{secrets.NPM_REGISTRY_NPM_REGISTRY_HARPOKRAT_NET_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - Bassintag
  ignore:
  - dependency-name: "@angular/compiler"
    versions:
    - 11.1.1
    - 11.1.2
    - 11.2.0
    - 11.2.1
    - 11.2.11
    - 11.2.2
    - 11.2.3
    - 11.2.4
    - 11.2.6
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: core-js
    versions:
    - 3.10.1
    - 3.8.3
    - 3.9.0
    - 3.9.1
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: stylelint
    versions:
    - 13.10.0
    - 13.11.0
    - 13.12.0
    - 13.9.0
  - dependency-name: rxjs
    versions:
    - 6.6.3
    - 6.6.6
  - dependency-name: zone.js
    versions:
    - 0.11.3
  - dependency-name: jasmine-core
    versions:
    - 3.6.0
  - dependency-name: jasmine-spec-reporter
    versions:
    - 6.0.0
  registries:
  - npm-registry-npm-registry-harpokrat-net
