apiVersion: v1
kind: Service
metadata:
  name: hpk-web-app
  labels:
    app: hpk-web-app
spec:
  ports:
    - port: 80
  selector:
    app: hpk-web-app
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: hpk-web-app
  labels:
    app: hpk-web-app
spec:
  selector:
    matchLabels:
      app: hpk-web-app
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hpk-web-app
        tier: frontend
    spec:
      containers:
      - image: gcr.io/harpokrat-275013/hpk-web-app-nginx:v0.0.2
        #imagePullPolicy: Never
        name: web-app-nginx
        ports:
        - containerPort: 80
          name: hpk-web-app
